volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: anime@email.com
      PGADMIN_DEFAULT_PASSWORD: anime@email.com
      PGADMIN_DISABLE_POSTFIX: 1

  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=contas,favoritos,watchlists
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    ports:
      - 15432:5432

  contas:
    build:
      context: ./contas
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./contas:/app
    environment:
      DATABASE_URL: postgresql://contas:password@postgres
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: LjdTjfrjPYgUJHNDzM-dKQoBLIfC74fNnR_71DcJcgE

  favoritos:
    build:
      context: ./favoritos
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./favoritos:/app
    environment:
      DATABASE_URL: postgresql://favoritos:password@postgres
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: LjdTjfrjPYgUJHNDzM-dKQoBLIfC74fNnR_71DcJcgE

  watchlists:
    build:
      context: ./watchlists
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./watchlists:/app
    environment:
      DATABASE_URL: postgresql://watchlists:password@postgres
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: LjdTjfrjPYgUJHNDzM-dKQoBLIfC74fNnR_71DcJcgE

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: Linux
      NODE_ENV: production
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNTS_API_HOST: http://localhost:8000
      REACT_APP_FAVORITES_API_HOST: http://localhost:8090
      REACT_APP_WATCHLISTS_API_HOST: http://localhost:8080
