version: "3.3"

services:
  animesite:
    build: .
    working_dir: /app
    volumes:
      - .:/app:rw
      - ./static:/app/static:ro 

    ports:
      - 8002:8000
    depends_on:
      - db
  db:
    container_name: mydb
    image: mysql:8.0
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 787114
      MYSQL_DATABASE: anime_date
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
